version: '3'

services:
  api:
    build:
      context: configs/backend
    command: gunicorn -c /etc/gunicorn.py app.main:http_app_factory
    ports:
      - 127.0.0.1:7000:8000
    volumes:
      - ./app:/app
    env_file:
      - .env

  redis:
    image: redis:5-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data: