version: '3'

services:
  api:
    build:
      context: configs/backend
    command: gunicorn -c /etc/gunicorn.py app.main:http_app_factory
    ports:
      - 7000:8000
    volumes:
      - ./app:/app
    env_file:
      - .env

#  proxy:
#    build:
#      context: configs/proxy
#    image: soundhound-proxy
#    container_name: soundhound-proxy
#    hostname: proxy
#    env_file:
#      - .env

  redis:
    image: redis:5-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data: